// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa19LvtB6nOh7NJhiX3qpx7o7DlwXAXTc',
    appId: '1:1073460920784:web:a33bb9079d2615c9c179d5',
    messagingSenderId: '1073460920784',
    projectId: 'interviewsendmoney',
    authDomain: 'interviewsendmoney.firebaseapp.com',
    storageBucket: 'interviewsendmoney.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDadmjNX8TYgR8QD4NkF7vgpCjsmJ1zEIY',
    appId: '1:1073460920784:android:349c0807cf931d5dc179d5',
    messagingSenderId: '1073460920784',
    projectId: 'interviewsendmoney',
    storageBucket: 'interviewsendmoney.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2EBJCtnNLA9vWoxPOvdbIga0yEYF34lQ',
    appId: '1:1073460920784:ios:beac67345f8ebf08c179d5',
    messagingSenderId: '1073460920784',
    projectId: 'interviewsendmoney',
    storageBucket: 'interviewsendmoney.firebasestorage.app',
    iosBundleId: 'com.example.sendmoneyInterview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2EBJCtnNLA9vWoxPOvdbIga0yEYF34lQ',
    appId: '1:1073460920784:ios:beac67345f8ebf08c179d5',
    messagingSenderId: '1073460920784',
    projectId: 'interviewsendmoney',
    storageBucket: 'interviewsendmoney.firebasestorage.app',
    iosBundleId: 'com.example.sendmoneyInterview',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCa19LvtB6nOh7NJhiX3qpx7o7DlwXAXTc',
    appId: '1:1073460920784:web:48af361e1cab181dc179d5',
    messagingSenderId: '1073460920784',
    projectId: 'interviewsendmoney',
    authDomain: 'interviewsendmoney.firebaseapp.com',
    storageBucket: 'interviewsendmoney.firebasestorage.app',
  );

}